# This file was generated by GoReleaser. DO NOT EDIT.
cask "zh" do
  name "zh"
  desc "CLI for ZenHub"
  homepage "https://github.com/dslh/zh"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zh"

  on_macos do
    on_intel do
      url "https://github.com/dslh/zh/releases/download/v#{version}/zh_#{version}_darwin_amd64.tar.gz"
      sha256 "13b0f5e87883fd1f50264491032cb6dac99c6929a9c0f58d2559ef2769a838dc"
    end
    on_arm do
      url "https://github.com/dslh/zh/releases/download/v#{version}/zh_#{version}_darwin_arm64.tar.gz"
      sha256 "6952de4971d239eacb652283f57d4ea769d13b6a57eb3fcb5888aba60cb564b3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dslh/zh/releases/download/v#{version}/zh_#{version}_linux_amd64.tar.gz"
      sha256 "dceeb21f11d4800c682e1cff50a3b4719cd44556884cd4eb753ae3f888fe9b00"
    end
    on_arm do
      url "https://github.com/dslh/zh/releases/download/v#{version}/zh_#{version}_linux_arm64.tar.gz"
      sha256 "279d9fe4a5468d186ee55462253cea8a01b45f8e357d02b1ef991d6a2cc33cf0"
    end
  end

  # No zap stanza required
end
