# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mm < Formula
  desc "CLI + MCP server for the mon-marché.fr grocery (cart only)"
  homepage "https://github.com/dslh/mm"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dslh/mm/releases/download/v1.0.1/mm_1.0.1_darwin_amd64.tar.gz"
      sha256 "1b7de34c52eeb8d9568aa4449ce6ca5f5671ea7fd4612345cb0258b3955f261c"

      define_method(:install) do
        bin.install "mm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dslh/mm/releases/download/v1.0.1/mm_1.0.1_darwin_arm64.tar.gz"
      sha256 "bf2ef3feea67a086670f2104878918206252a86a124f8f81e1c99c80097b0e5b"

      define_method(:install) do
        bin.install "mm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dslh/mm/releases/download/v1.0.1/mm_1.0.1_linux_amd64.tar.gz"
      sha256 "885b840fd2521d552df4156b127efe6c6963c5b2b01ff43377a2170e2d88faef"
      define_method(:install) do
        bin.install "mm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dslh/mm/releases/download/v1.0.1/mm_1.0.1_linux_arm64.tar.gz"
      sha256 "cc20c2f27c2544f0bd174ce37c30291754f7a4b8140fc94c493917b8aa777761"
      define_method(:install) do
        bin.install "mm"
      end
    end
  end

  test do
    system "#{bin}/mm", "version"
  end
end
