# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mm < Formula
  desc "CLI + MCP server for the mon-marché.fr grocery (cart only)"
  homepage "https://github.com/dslh/mm"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dslh/mm/releases/download/v1.0.0/mm_1.0.0_darwin_amd64.tar.gz"
      sha256 "c6c2c2f938a6ec6969366238f36726af4adbaa7eb95d3a319133477f6cf9de80"

      define_method(:install) do
        bin.install "mm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dslh/mm/releases/download/v1.0.0/mm_1.0.0_darwin_arm64.tar.gz"
      sha256 "dd323d15a60eed5b64877b72807a5fff2f19d0dd0a054ea29d890a42e306147d"

      define_method(:install) do
        bin.install "mm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dslh/mm/releases/download/v1.0.0/mm_1.0.0_linux_amd64.tar.gz"
      sha256 "7a6a2e95fd9b52a6de6bc4f5e1fa4f9d1ec134623e0ab08253c966680c320975"
      define_method(:install) do
        bin.install "mm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dslh/mm/releases/download/v1.0.0/mm_1.0.0_linux_arm64.tar.gz"
      sha256 "28e12d569a47487ecae8f9a8cd61986f584ce8b94147f1c17245c087a7ec5c27"
      define_method(:install) do
        bin.install "mm"
      end
    end
  end

  test do
    system "#{bin}/mm", "version"
  end
end
