# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zh < Formula
  desc "CLI for ZenHub"
  homepage "https://github.com/dslh/zh"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dslh/zh/releases/download/v1.0.0/zh_1.0.0_darwin_amd64.tar.gz"
      sha256 "dc48d49cf3ea63d692db64b42a27b5c6405bcac575e95e4d6858df5321ff7f25"

      def install
        bin.install "zh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dslh/zh/releases/download/v1.0.0/zh_1.0.0_darwin_arm64.tar.gz"
      sha256 "7c68c062e3c239850e95ecfe5ffaa96227702f85a3f6055fe9c74a1d578e0688"

      def install
        bin.install "zh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dslh/zh/releases/download/v1.0.0/zh_1.0.0_linux_amd64.tar.gz"
      sha256 "a8e93636550c265114f72809c729b3c880b04337c8489bc6ea7c5e3aa040fb8a"
      def install
        bin.install "zh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dslh/zh/releases/download/v1.0.0/zh_1.0.0_linux_arm64.tar.gz"
      sha256 "3ac3e79e5b7346c3a1593c54c95c87d6909a917dd8ceede0d331dbeb87ac5339"
      def install
        bin.install "zh"
      end
    end
  end

  test do
    system "#{bin}/zh", "version"
  end
end
