# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zh < Formula
  desc "CLI for ZenHub"
  homepage "https://github.com/dslh/zh"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dslh/zh/releases/download/v1.0.4/zh_1.0.4_darwin_amd64.tar.gz"
      sha256 "2d241bd08d82a645c32956eb71d584ac2404aff74545e4a43e0e66d72c5f625c"

      def install
        bin.install "zh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dslh/zh/releases/download/v1.0.4/zh_1.0.4_darwin_arm64.tar.gz"
      sha256 "373b53c4a9211537ec37261a3ac37a6644b539d6b45ecd7ed9acd36102577c2e"

      def install
        bin.install "zh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dslh/zh/releases/download/v1.0.4/zh_1.0.4_linux_amd64.tar.gz"
      sha256 "f0459de65e194dda59c26385a8df64b547052015b3ef2bff2571bd342fb7a5ed"
      def install
        bin.install "zh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dslh/zh/releases/download/v1.0.4/zh_1.0.4_linux_arm64.tar.gz"
      sha256 "f1b4315dff37b996d88eadb77de52d276fd5c2c7b8a170d21f94c4075eca864e"
      def install
        bin.install "zh"
      end
    end
  end

  test do
    system "#{bin}/zh", "version"
  end
end
