# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zh < Formula
  desc "CLI for ZenHub"
  homepage "https://github.com/dslh/zh"
  version "1.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dslh/zh/releases/download/v1.0.9/zh_1.0.9_darwin_amd64.tar.gz"
      sha256 "b037d58640b78b15601d6da9ee625187bb96f57125d96889d0aee77f0fee0954"

      define_method(:install) do
        bin.install "zh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dslh/zh/releases/download/v1.0.9/zh_1.0.9_darwin_arm64.tar.gz"
      sha256 "044b88420c3d8757a22c030190c03cbd8bf63ba8000937abce315e1a19e7512d"

      define_method(:install) do
        bin.install "zh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dslh/zh/releases/download/v1.0.9/zh_1.0.9_linux_amd64.tar.gz"
      sha256 "3d460f36727e25c4bbaf5cd15b6aec77cbc7df00d065c1e5bfefd18b70c02458"
      define_method(:install) do
        bin.install "zh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dslh/zh/releases/download/v1.0.9/zh_1.0.9_linux_arm64.tar.gz"
      sha256 "c88b9a632103bc486dbaa2d14ef82a8d73fdf43707dd1bf652c2610510a05413"
      define_method(:install) do
        bin.install "zh"
      end
    end
  end

  test do
    system "#{bin}/zh", "version"
  end
end
